function [ a ] = visualize_mats( GT, Pred, C, AffinityMat, Z, D, E )
    subplot(3, 4, 1)
    imagesc(GT)
    title('Subplot 1: GT')
    subplot(3, 4, 2)
    imagesc(Pred)
    title('Subplot 2: Pred')
    subplot(3, 4, 3)
    imagesc(C)
    title('Subplot 3: C')
    subplot(3, 4, 4)
    imagesc(AffinityMat)
    title('Subplot 4: CDmean')
    subplot(3, 4, 5)
    imagesc(Z{1})
    title('Subplot 5: Z{1}')
    subplot(3, 4, 6)
    imagesc(Z{2})
    title('Subplot 6: Z{2}')
    subplot(3, 4, 7)
    imagesc(Z{3})
    title('Subplot 7: Z{3}')
    subplot(3, 4, 8)
    imagesc(D{1})
    title('Subplot 8: D{1}')
    subplot(3, 4, 9)
    imagesc(D{2})
    title('Subplot 9: D{2}')
    subplot(3, 4, 10)
    imagesc(D{3})
    title('Subplot 10: D{3}')
    if nargin > 6
        subplot(3, 4, 11)
        imagesc(E{1})
        title('Subplot 11: E{1}')
        subplot(3, 4, 12)
        imagesc(E{2})
        title('Subplot 12: E{2}')
        subplot(3, 4, 13)
        imagesc(E{3})
        title('Subplot 13: E{3}')
    end
    a = 1;
end

